[package]
name = "micro"
version = "0.1.0"
edition = "2024"

[dependencies]
diesel = { version = "2.2.0", features = ["postgres_backend", "postgres", "chrono"]}
infra = { git = "https://github.com/soniapi/infra.git" }
prop = { git = "https://github.com/soniapi/prop.git" }
dotenvy = "0.15"

[patch."https://github.com/soniapi/prop.git"]
infra = { git = "https://github.com/soniapi/infra.git" }
